### PR TITLE
activate failed htlc payment pruning

### LINKED ISSUE #573: delete failed payment on lnd
now that we are on lnd 0.13, I think we can activate the deletion of failed payment on the cron job

### PR DESCRIPTION
**Pull request by nicolasburtey**
fix #573 (at least the failed htlc). 

we might want to dive more into the use of the `deletefailedpayments` (instead of `deleteFailedPayAttempts`), because it's possible we need the data about failed payments for support purpose. ie: when we need to do a refund.

the htlc part are safe to delete, and would likely already free the database significantly.

### CODE REVIEW

File: src/services/lnd/index.ts [hunk 1]
```diff
@@ -102,5 +108,6 @@ export const LndService = (): ILightningService | LightningServiceError => {
     registerInvoice,
     lookupInvoice,
     lookupPayment,
+    deleteFailedPayAttempts,
```
Comment (bodymindarts) [inline src/services/lnd/index.ts:111]: Where is this being called? the `LndService` function should only return an object fulfilling [this](https://github.com/GaloyMoney/galoy/blob/main/src/domain/ledger/index.types.d.ts#L87) interface. Which in turn only defines functions that are being used in `src/app` use-cases. IE its part of the re-worked, clean code.
This is why `check-code` is failing.

If you want to add it here you should be wrapping the code with the same `try/catch` + error pattern we have been using in the other cleaned up code sections - but that really depends on where / how its being called.

**Comment by bodymindarts** [comment]
Change looks simple - has this been tested at all? If so how?

**Review by bodymindarts — DISMISSED** [review]

File: src/services/lnd/utils.ts [hunk 2]
```diff
@@ -53,16 +50,15 @@ export const deleteExpiredInvoiceUser = async () => {
...
-  //     await deleteFailedPayments({lnd})
-  //   }
-  // } catch (err) {
-  //   baseLogger.warn({ err }, "error deleting failed payment")
-  // }
+  const lnds = offchainLnds
+  for (const { lnd, socket } of lnds) {
+    try {
+      baseLogger.info({ socket }, "running deleteFailedPayments")
+      await deleteFailedPayAttempts({ lnd })
```
Comment (dolcalmi) [inline src/services/lnd/utils.ts:57]: do we want to delete only payment attemps or failed payments too? https://github.com/alexbosworth/ln-service#deletefailedpayments

Comment (krtk6160) [reply src/services/lnd/utils.ts:57]: I have the same question as @dolcalmi. If we're only deleting failed payment attempts then we should also rename the function and change the log message accordingly.

**Review by krtk6160 — CHANGES_REQUESTED** [review]

File: src/services/lnd/utils.ts (hunk 2 above)
Comment (nicolasburtey) [reply src/services/lnd/utils.ts:57]: @dolcalmi eventually we want to delete all failed payment, but starting with the payment attempt is less risky.

I'm not sure yet if there would be some side effect of deleting failed payment for the refund. but deleting payment attempt should have no effect

I'll do the renaming

**Review by dolcalmi — DISMISSED** [review]

File: src/services/lnd/utils.ts [hunk 3]
```diff
@@ -1,39 +1,36 @@
+import {
```
Comment (nicolasburtey) [inline src/services/lnd/utils.ts:1]: it feels my vs code wants to change import order. is there a way a setting to fix this @samerbuna ?

**Review by bodymindarts — APPROVED** [review]

File: src/services/lnd/utils.ts (hunk 3 above)
Comment (samerbuna) [reply src/services/lnd/utils.ts:1]: It would be somewhere in your saved settings - cmd+shift+p, open settings(json)

Inspect that for any sort/organize settings for imports
